### ISSUE TITLE
Autoconfiguration

### ISSUE THREAD

**Issue by slavaGanzin** [dhth/act3#4]
Hello Dhruv. Thanks for act3!

I was a bit surprised, that you need to create a configuration to use act3. What I was expecting is that it will read `pwd`/.github/workflows and show stats for all CI files per project. 

Your approach makes perfect sense. But it would be beneficial to combine both. If you launch act3 in a folder that contains CI files that are not listed in configuration, act3 could ask do you want to add new files to config.
```bash
$ cd /my/new/project
$ act3
Do you want to add "Build and release" workflow for slava/project to act3? (Y/n)
Y
- id: W_kwDOLkC0eM4FaKV_
  repo: slava/project
  name: build_and_release
# Added to ~/.config/act3/act3.yml
```

Kinda like that. What do you think?

p.s. Can I put ACT3 GH access token in config as well?

**Comment by dhth** [comment]
Hey!
I like the idea of using a repository's own `.github/workflows/*.yml` to use as input for `act3` 👍
I'll add support for that.

Not at the moment, it's only via an env variable. I might add support for piggybacking off of `gh`, which will remove any need for explicitly providing a token.

*All of this might take a few days, given my current workload.*

**Comment by dhth** [comment]
Using the current directory as input has been made the default behaviour for `act3` in [v1.0.0](https://github.com/dhth/act3/releases/tag/v1.0.0).

**Comment by slavaGanzin** [comment]
Works for me!
